name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
     contents: write
     packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "15"
          feed_list: "https://medium.com/feed/@StevenBoylan"
