name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stevenboylan/blog-post-workflow@master
        with:
          max_post_count: "15"
          feed_list: "https://medium.com/feed/@StevenBoylan"
